config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :authors do 
    get "/api_show" , to: "authors#api_show"

  end
  resources :books
  root "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors
	validates :first_name, presence:true, length: {minimum: 3, maximum:20}
	validates :last_name, presence:true, length: {minimum: 3, maximum:20}
	 validate :date_of_birth_greater_than_10_years_ago

  def date_of_birth_greater_than_10_years_ago
    if date_of_birth.present? && date_of_birth > 10.years.ago.to_date
      errors.add(:date_of_birth, "must be greater than 10 years ago")
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :book_authors
	has_many :authors, through: :book_authors
	validates :title, presence:true, length: {minimum: 4, maximum:20}
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
	belongs_to :book
	belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController


	def index
		@authors = Author.all
	end




	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		if @author.save
			flash[:notice]="Welcome to the library management #{@author.first_name}, you have successfully signed up"
    		redirect_to authors_path
    	else
    	    render 'new'	
    	end 

	end



	def show
		@author = Author.find(params[:id])
		
	end

	def edit
    	@author = Author.find(params[:id])
    end

    def update
    	@author = Author.find(params[:id])
    	if @author.update(author_params)
    		flash[:notice]="Author profile was updated succesfully"
    		redirect_to author_path
    	end	
    end

    def destroy
    	@author = Author.find(params[:id])
    	@author.destroy
    	redirect_to authors_path
    end

    def api_show
		@author = Author.find(params[:author_id])
		render json: @author, include: :books
	end



private

def author_params
	params.require(:author).permit(:first_name,:last_name,:date_of_birth)
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@book = Book.new
	end

    def create
    	@book = Book.new(book_params)
    	if @book.save
    		flash[:notice]="Book was created succesfully"
    		redirect_to books_path
    	else
    	    render 'new'	
    	end    
    end

    def index
    	@books = Book.all
    end

     def show
    	@book = Book.find(params[:id])
    	
    end


    def edit
    	@book = Book.find(params[:id])
    end


    def update
    	@book = Book.find(params[:id])
    	if @book.update(book_params)
    		flash[:notice]="Book was updated succesfully"
    		redirect_to books_path
    	end	
    end

    def destroy
    	@book = Book.find(params[:id])
    	@book.destroy
    	redirect_to books_path
    end	


    private


    def book_params
		params.require(:book).permit(:title, author_ids: [])
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_author.html.erb
<div style="display: inline;">
  <%= link_to author.first_name, author_path(author), class: "badge text-bg-dark", style: "display: inline-block; background-color: darkgray; color: white; padding: 5px 10px; text-decoration: none;" %>
</div>

app/views/authors/edit.html.erb
<div class="card-body">
  <div class="container-fluid">
    <div class="row">
    <div class="col-md-3"></div>
      <div class="col-md-6"><br>
        <div class="card">
            <div class="card-body">
               <h3 class="text-center mt-4">Edit Author</h3>
                  <%= form_with model: @author do |f|%>
                  <div>
                     <%= f.label :First_Name %><br>
                     <%= f.text_field :first_name, class: "form-control"  %>
                     <%= f.label :Last_Name %><br>
                     <%= f.text_field :last_name, class: "form-control"  %>
                     <%= f.label :Date_of_Birth %><br>
                     <%= f.date_field :date_of_birth, class: "form-control"  %><br>
                   </div>
                   <div>
                  <%= f.submit class:"btn btn-outline-success" %>
                  </div>
  <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/authors/index.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6">
    <h3 class="my-3">Author Listing</h3>

    <% @authors.each do |author| %>
      <div class="card mb-2">
        <div class="card-body">
          <h4 class="card-title"> <%=link_to 'Author name:',author_path(author)%> <%=author.first_name %> <%=  author.last_name%></h4>
          <p>Date of Birth: <%= author.date_of_birth %></p>
        </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/authors/new.html.erb
<div class="card-body">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
    <h3>Add Author</h3>
  <%= form_with model: @author do |f|%>
  <div>
       <%= f.label :First_Name %><br>
       <%= f.text_field :first_name, class: "form-control"  %><br>
       <%= f.label :Last_Name %><br>
       <%= f.text_field :last_name, class: "form-control"  %><br>
       <%= f.label :Date_of_Birth %><br>
       <%= f.date_field :date_of_birth, class: "form-control"  %><br>

    </div>
    <div>
       <%= f.submit class:"btn btn-outline-success" %>
    </div>
  <% end %>
</div>
<div class="col-md-3"></div>
</div>
</div>

app/views/authors/show.html.erb
<br><div class="container">
  <div class="d-flex align-items-center">
    <div class="card mx-auto" style="max-width: 1000px;">
      <div class="card-body text-center">
        <h4 class="card-title"><%= @author.first_name %> <%= @author.last_name %></h4>
        <p class="card-text">Date of Birth: <%= @author.date_of_birth %></p>

        <div class="btn-group">
          <%= link_to 'Edit Profile', edit_author_path(@author), class: "btn btn-outline-success" %> &nbsp
          <%= button_to 'Delete Profile', author_path(@author), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="card-body">
  <div class="container">
    <h3>Edit Book</h3>
  <%= form_with model: @book do |f|%>
  <div>
       <%= f.label :title %><br>
       <%= f.text_field :title, class: "form-control"  %>
    </div>
    <div>
      <div>
                        <%= f.label :Authors %><br>
                        <%= f.collection_select(:author_ids, Author.all, :id, :first_name,
                        { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, class: "custom-select form-control" }) %><br>
                      </div>








       <%= f.submit class:"btn btn-outline-success" %>
       <%= button_to 'Delete',book_path(@book), data: {turbo_method: :delete}, class: "btn btn-outline-danger"%> 
    </div>
  <% end %>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3"></div>
  	<div class="col-md-6">
    <h3 class="my-3">Book Listing</h3>
    <%= link_to "Create new Book", new_book_path, class: "btn btn-outline-info" %><br>
      <br>
    <% @books.each do |book| %>
      <div class="card mb-3">
        <div class="card-body">
          <h4 class="card-title"><%= link_to book.title, book_path(book), class: "text-success" %></h4>
          <div><% if book.authors.any? %>
                             <%= render book.authors %>
                       <% end %></div><br>
          <div class="btn-group">
            <%= button_to 'View Book', book_path(book) ,method: :get, class: "btn btn-outline-info" %>&nbsp
            <%= button_to 'Edit Book', edit_book_path(book) ,method: :get, class: "btn btn-outline-success" %>&nbsp
            <%= button_to 'Delete', book_path(book), method: :delete, class: "btn btn-outline-danger" %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/books/new.html.erb
<div class="card-body">
  <div class="container">
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
       <h3>Add Book</h3>
        <%= form_with model: @book do |f|%>
        <div>
           <%= f.label :title %><br>
           <%= f.text_field :title, class: "form-control"  %>
        </div>

         <div>
                        <%= f.label :Authors %><br>
                        <%= f.collection_select(:author_ids, Author.all, :id, :first_name,
                        { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, class: "custom-select form-control" }) %><br>
                      </div>


       <br><%= f.submit class:"btn btn-outline-success" %>
  <% end %>
  </div>
  <div class="col-md-3"></div>
</div>
</div>

app/views/books/show.html.erb
<br><div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h3 class="text-center">Book Details</h3>
            
               <div class="card">
                  <div class="card-body text-center">


                         Book name: <%= @book.title %><br><br>
                          <div>
                            <% if @book.authors.any? %>
                                     <%= render @book.authors %>
                               <% end %></div>
                               <br>
                          <div class="btn-group">
                                  <%= button_to 'Edit Book', edit_book_path(@book) ,method: :get, class: "btn btn-outline-success" %>&nbsp
                                   <%= button_to 'Delete', book_path(@book),method: :delete, class: "btn btn-outline-danger" %>
                            </div>       
                   </div>
               
            </div>
            </div>
        <div class="col-md-3"></div>
    </div>        
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Library', root_path, class: "nav-link" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: "nav-link" %>

        </li>
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Create new profile", new_author_path, class: "dropdown-item" %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<div id="page-content">
<div class="container" style="margin-top: 2rem;" id="jumbotron1">
        <div class="jumbotron1 text-right">
              <h1 class="display-4 ">Library Management </h1>
              <p class="lead"> </p>
              <hr class="my-4">
             
              
        </div>
    </div>
</div>